/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.SystemAdminWorkspace;

import Hospital.Doctor.DoctorDirectory;
import Hospital.Encounter.Encounter;
import Hospital.Encounter.EncounterDirectory;
import Hospital.Hospital.Hospital;
import Hospital.Hospital.HospitalDirectory;
import Hospital.Patient.PatientDirectory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ui.PatientWorkspace.PatientDashboard;

/**
 *
 * @author kishor
 */
public class SystemEncounterPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemEncounterPanel
     */
    EncounterDirectory encounterList;
    HospitalDirectory hospitalList;
    PatientDirectory patientList;
    DoctorDirectory doctorList;
    
    public SystemEncounterPanel(EncounterDirectory encounterList,HospitalDirectory hospitalList,PatientDirectory patientList,DoctorDirectory doctorList) {
        initComponents();
        this.encounterList = encounterList;
        this.hospitalList = hospitalList;
        this.patientList = patientList;
        this.doctorList = doctorList;
        
        populateTable();
        populateHospital();
        populateDoctor();
        populatePatient();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnEdit1 = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        scrollPaneEncounter = new javax.swing.JScrollPane();
        tableEncounter = new javax.swing.JTable();
        txtEncounterNo = new javax.swing.JTextField();
        lblEncounterNo = new javax.swing.JLabel();
        lblDoctorName = new javax.swing.JLabel();
        lblDoctorUsername = new javax.swing.JLabel();
        lblPatientName = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblRoomNo = new javax.swing.JLabel();
        txtRoomNo = new javax.swing.JTextField();
        txtDoctorName = new javax.swing.JComboBox<>();
        txtDoctorUsername = new javax.swing.JComboBox<>();
        txtPatientusername = new javax.swing.JComboBox<>();
        txtPatientName = new javax.swing.JComboBox<>();
        lblRoomNo1 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        lblTime = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        lblHospital = new javax.swing.JLabel();
        txtHospital = new javax.swing.JComboBox<>();
        lblComments = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtComment = new javax.swing.JTextArea();

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("Encounter Screen");

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnEdit1.setText("Edit");
        btnEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit1ActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        tableEncounter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Encounter No", "Doctor", "Patient", "Room No", "Date", "Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrollPaneEncounter.setViewportView(tableEncounter);

        txtEncounterNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEncounterNoActionPerformed(evt);
            }
        });

        lblEncounterNo.setText("Encounter No:");

        lblDoctorName.setText("Doctor Name:");

        lblDoctorUsername.setText("Doctor Username:");

        lblPatientName.setText("Patient Name:");

        lblCity.setText("Patient Username:");

        lblRoomNo.setText("Room No: ");

        txtRoomNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoomNoActionPerformed(evt);
            }
        });

        lblRoomNo1.setText("Date: ");

        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblTime.setText("Time:");

        lblHospital.setText("Hospital:");

        lblComments.setText("Comments:");

        txtComment.setColumns(20);
        txtComment.setRows(5);
        jScrollPane1.setViewportView(txtComment);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDoctorUsername)
                            .addComponent(lblPatientName)
                            .addComponent(lblDoctorName)
                            .addComponent(lblHospital)
                            .addComponent(lblEncounterNo))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEncounterNo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtDoctorUsername, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDoctorName, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPatientName, 0, 149, Short.MAX_VALUE)
                                .addComponent(txtHospital, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCity)
                                    .addComponent(lblRoomNo1)
                                    .addComponent(lblRoomNo)
                                    .addComponent(lblComments)
                                    .addComponent(lblTime))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtDate)
                                        .addComponent(txtRoomNo, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                        .addComponent(txtTime, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                        .addComponent(txtPatientusername, 0, 149, Short.MAX_VALUE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnClear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSave)))
                        .addGap(75, 75, 75))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(233, 233, 233)
                                .addComponent(lblTitle))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(76, 76, 76)
                                .addComponent(scrollPaneEncounter, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitle)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCreate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnView)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete))
                    .addComponent(scrollPaneEncounter, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPatientusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCity))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRoomNo)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(lblRoomNo1)))
                        .addGap(18, 18, 18)
                        .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEncounterNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEncounterNo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHospital)
                            .addComponent(txtHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDoctorName)
                            .addComponent(txtDoctorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDoctorUsername)
                            .addComponent(txtDoctorUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTime))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPatientName)
                            .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblComments))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear)
                    .addComponent(btnSave))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        //        btnClear.setVisible(false);
        String encounterNo = txtEncounterNo.getText();
        String hospital = String.valueOf(txtHospital.getSelectedItem());
        String doctorName = String.valueOf(txtDoctorName.getSelectedItem());
        String doctorUsername = String.valueOf(txtDoctorUsername.getSelectedItem());
        String patientName = String.valueOf(txtPatientName.getSelectedItem());
        String patientUsername = String.valueOf(txtPatientusername.getSelectedItem());
        Integer roomNo = Integer.parseInt(txtRoomNo.getText());
        String date = txtDate.getText();
        String time = txtTime.getText();
        String comment = txtComment.getText();

        Encounter newEncounter = encounterList.addEncounter();

        newEncounter.setEncounterNo(encounterNo);
        newEncounter.setHospital(hospital);
        newEncounter.setDoctorName(doctorName);
        newEncounter.setDoctorUserName(doctorUsername);
        newEncounter.setPatientName(patientName);
        newEncounter.setPatientUsername(patientUsername);
        newEncounter.setRooomNo(roomNo);
        newEncounter.setDate(date);
        newEncounter.setTime(time);
        newEncounter.setComment(comment);

        JOptionPane.showMessageDialog(this, "Encounter Created Successfully");

        txtEncounterNo.setText("");
        txtHospital.setSelectedIndex(0);
        txtDoctorName.setSelectedIndex(0);
        txtDoctorUsername.setSelectedIndex(0);
        txtPatientName.setSelectedIndex(0);
        txtPatientusername.setSelectedIndex(0);
        txtRoomNo.setText("");
        txtDate.setText("");
        txtTime.setText("");
        txtComment.setText("");

        populateTable();
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        //        btnSave.setVisible(false);
        btnClear.setVisible(true);
        Integer selectedRowIndex = tableEncounter.getSelectedRow();

        if (selectedRowIndex<0){

            JOptionPane.showMessageDialog(this, "Please select a row to view.");
            return;
        }

        else{
            DefaultTableModel model = (DefaultTableModel) tableEncounter.getModel();
            Encounter selectedEn = (Encounter) model.getValueAt(selectedRowIndex,0);

            txtEncounterNo.setText(selectedEn.getEncounterNo());
            txtHospital.setSelectedItem(selectedEn.getHospital());
            txtDoctorName.setSelectedItem(selectedEn.getDoctorName());
            txtDoctorUsername.setSelectedItem(selectedEn.getDoctorUserName());
            txtPatientName.setSelectedItem(selectedEn.getPatientName());
            txtPatientusername.setSelectedItem(selectedEn.getPatientUsername());
            txtRoomNo.setText(String.valueOf(selectedEn.getRooomNo()));
            txtDate.setText(selectedEn.getDate());
            txtTime.setText(selectedEn.getTime());
            txtComment.setText(selectedEn.getComment());

        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit1ActionPerformed
        // TODO add your handling code here:
        btnSave.setVisible(true);
        btnClear.setVisible(true);
        
        Integer selectedRowIndex = tableEncounter.getSelectedRow();

        if (selectedRowIndex<0){

            JOptionPane.showMessageDialog(this, "Please select a row to view.");
            return;
        }

        else{
            DefaultTableModel model = (DefaultTableModel) tableEncounter.getModel();
            Encounter selectedEn = (Encounter) model.getValueAt(selectedRowIndex,0);

            txtEncounterNo.setText(selectedEn.getEncounterNo());
            txtHospital.setSelectedItem(selectedEn.getHospital());
            txtDoctorName.setSelectedItem(selectedEn.getDoctorName());
            txtDoctorUsername.setSelectedItem(selectedEn.getDoctorUserName());
            txtPatientName.setSelectedItem(selectedEn.getPatientName());
            txtPatientusername.setSelectedItem(selectedEn.getPatientUsername());
            txtRoomNo.setText(String.valueOf(selectedEn.getRooomNo()));
            txtDate.setText(selectedEn.getDate());
            txtTime.setText(selectedEn.getTime());
            txtComment.setText(selectedEn.getComment());

        }

    }//GEN-LAST:event_btnEdit1ActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        btnClear.setVisible(false);
        Integer selectedRowIndex = tableEncounter.getSelectedRow();

        if (selectedRowIndex<0){

            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
            return;
        }

        else{
            DefaultTableModel model = (DefaultTableModel) tableEncounter.getModel();
            Encounter selectedEn = (Encounter) model.getValueAt(selectedRowIndex,0);

            encounterList.deleteEncounter(selectedEn);

            JOptionPane.showMessageDialog(this, "Encounter deleted successfully.");
            
            populateTable();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtEncounterNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEncounterNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEncounterNoActionPerformed

    private void txtRoomNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoomNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoomNoActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtEncounterNo.setText("");
        txtHospital.setSelectedIndex(0);
        txtDoctorName.setSelectedIndex(0);
        txtDoctorUsername.setSelectedIndex(0);
        txtPatientName.setSelectedIndex(0);
        txtPatientusername.setSelectedIndex(0);
        txtRoomNo.setText("");
        txtDate.setText("");
        txtTime.setText("");
        txtComment.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        Integer selectedRowIndex = tableEncounter.getSelectedRow();

        if (selectedRowIndex<0){

            JOptionPane.showMessageDialog(this, "Please select a row to view.");
            return;
        }

        else{
            DefaultTableModel model = (DefaultTableModel) tableEncounter.getModel();
            Encounter selectedEn = (Encounter) model.getValueAt(selectedRowIndex,0);
            
            selectedEn.setEncounterNo(txtEncounterNo.getText());
            selectedEn.setHospital(String.valueOf(txtHospital.getSelectedItem()));
            selectedEn.setDoctorName(String.valueOf(txtDoctorName.getSelectedItem()));
            selectedEn.setDoctorUserName(String.valueOf(txtDoctorUsername.getSelectedItem()));
            selectedEn.setPatientName(String.valueOf(txtPatientName.getSelectedItem()));
            selectedEn.setPatientUsername(String.valueOf((txtPatientusername.getSelectedItem())));
            selectedEn.setRooomNo(Integer.parseInt(txtRoomNo.getText()));
            selectedEn.setDate(txtDate.getText());
            selectedEn.setTime(txtTime.getText());
            selectedEn.setComment(txtComment.getText());

            

            JOptionPane.showMessageDialog(this, "Encounter details updated successfully.");

            populateTable();

        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) tableEncounter.getModel();
        model.setRowCount(0);
        
        for(Encounter en : encounterList.getEncounterList()){
            
            Object[] row = new Object[6];
            row[0] = en; 
            row[1] = en.getHospital();
            row[2] = en.getDoctorName();
            row[3] = en.getPatientName();
            row[4] = en.getDate();
            row[5] = en.getTime();
           
             
            model.addRow(row);
        }
    }
    
    public void populateHospital(){
        String[] hosArr = hospitalList.hosArray();
        DefaultComboBoxModel h = new DefaultComboBoxModel(hosArr);
        txtHospital.setModel(h);
    }
    
    public void populateDoctor(){
        String[] docNameArr = doctorList.docNameArray();
        DefaultComboBoxModel dn = new DefaultComboBoxModel(docNameArr);
        txtDoctorName.setModel(dn);
        
        String[] docUnameArr = doctorList.docUnameArray();
        DefaultComboBoxModel du = new DefaultComboBoxModel(docUnameArr);
        txtDoctorUsername.setModel(du);   
    }
    
    public void populatePatient(){
        String[] patNameArr = patientList.patNameArray();
        DefaultComboBoxModel pn = new DefaultComboBoxModel(patNameArr);
        txtPatientName.setModel(pn);
        
        String[] patUnameArr = patientList.patUnameArray();
        DefaultComboBoxModel pu = new DefaultComboBoxModel(patUnameArr);
        txtPatientusername.setModel(pu);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit1;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblComments;
    private javax.swing.JLabel lblDoctorName;
    private javax.swing.JLabel lblDoctorUsername;
    private javax.swing.JLabel lblEncounterNo;
    private javax.swing.JLabel lblHospital;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblRoomNo;
    private javax.swing.JLabel lblRoomNo1;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JScrollPane scrollPaneEncounter;
    private javax.swing.JTable tableEncounter;
    private javax.swing.JTextArea txtComment;
    private javax.swing.JTextField txtDate;
    private javax.swing.JComboBox<String> txtDoctorName;
    private javax.swing.JComboBox<String> txtDoctorUsername;
    private javax.swing.JTextField txtEncounterNo;
    private javax.swing.JComboBox<String> txtHospital;
    private javax.swing.JComboBox<String> txtPatientName;
    private javax.swing.JComboBox<String> txtPatientusername;
    private javax.swing.JTextField txtRoomNo;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables
}
