/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.DoctorWorkspace;

import Hospital.Doctor.Doctor;
import Hospital.Doctor.DoctorDirectory;
import Hospital.Encounter.Encounter;
import Hospital.Encounter.EncounterDirectory;
import Hospital.Hospital.HospitalDirectory;
import Hospital.Patient.PatientDirectory;
import Hospital.VitalSigns.VitalSign;
import Hospital.VitalSigns.VitalSignDirectory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ui.PatientWorkspace.PatientDashboard;

/**
 *
 * @author kishor
 */
public class DoctorVitalSignsPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorVitalSignsPanel
     */
    private VitalSignDirectory vitalSignList;
    private EncounterDirectory encounterList;
    private HospitalDirectory hospitalList;
    private PatientDirectory patientList;
    private DoctorDirectory doctorList;
    private Doctor doctor;

    public DoctorVitalSignsPanel(Doctor doctor, VitalSignDirectory vitalSignList, EncounterDirectory encounterList, HospitalDirectory hospitalList, PatientDirectory patientList, DoctorDirectory doctorList) {
        initComponents();
        this.vitalSignList = vitalSignList;
        this.encounterList = encounterList;
        this.hospitalList = hospitalList;
        this.doctorList = doctorList;
        this.patientList = patientList;
        this.doctor = doctor;
        txtDoctor.setText(doctor.getUsername());
        populateTable();
        populateEncounter();
        populateHospital();
        populatePatient();

        btnClear.setVisible(false);
        btnSave.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreate = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnEdit1 = new javax.swing.JButton();
        scrollPaneEncounter = new javax.swing.JScrollPane();
        tableVS = new javax.swing.JTable();
        lblEncounterNo = new javax.swing.JLabel();
        lblCreatedBy = new javax.swing.JLabel();
        lblPatientName = new javax.swing.JLabel();
        txtPatientName = new javax.swing.JComboBox<>();
        lblHospital = new javax.swing.JLabel();
        txtHospital = new javax.swing.JComboBox<>();
        lblBloodGroup = new javax.swing.JLabel();
        txtBloodGroup = new javax.swing.JComboBox<>();
        lblPresc = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPrescription = new javax.swing.JTextArea();
        btnClear = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        txtDoctor = new javax.swing.JTextField();
        lblBP = new javax.swing.JLabel();
        txtBp = new javax.swing.JTextField();
        txtPulse = new javax.swing.JTextField();
        lblPulse = new javax.swing.JLabel();
        lblTemp = new javax.swing.JLabel();
        txtTemp = new javax.swing.JTextField();
        txtEncounterNo = new javax.swing.JComboBox<>();
        txtPatientUname = new javax.swing.JComboBox<>();
        lblPatientUname = new javax.swing.JLabel();
        lbltitle1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnEdit1.setText("Edit");
        btnEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit1ActionPerformed(evt);
            }
        });

        tableVS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Encounter No", "Patient", "Blood Group", "BP", "Pulse", "Temperature"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrollPaneEncounter.setViewportView(tableVS);

        lblEncounterNo.setText("Encounter No:");

        lblCreatedBy.setText("Created By:");

        lblPatientName.setText("Patient Name:");

        lblHospital.setText("Hospital:");

        lblBloodGroup.setText("Blood Group:");

        txtBloodGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "A+", "B+", "O+", "AB+", "A-", "B-", "O-", "AB-" }));

        lblPresc.setText("Prescription:");

        txtPrescription.setColumns(20);
        txtPrescription.setRows(5);
        jScrollPane1.setViewportView(txtPrescription);

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtDoctor.setEditable(false);
        txtDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoctorActionPerformed(evt);
            }
        });

        lblBP.setText("BP:");

        lblPulse.setText("Pulse:");

        lblTemp.setText("Temperature:");

        txtEncounterNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEncounterNoActionPerformed(evt);
            }
        });

        lblPatientUname.setText("Patient Username:");

        lbltitle1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        lbltitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitle1.setText("DOCTOR ADMIN: VITAL SIGNS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCreatedBy)
                                    .addComponent(lblBloodGroup))
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtPatientName, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtHospital, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtEncounterNo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPatientUname, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPatientName)
                                    .addComponent(lblHospital)
                                    .addComponent(lblEncounterNo)
                                    .addComponent(lblPatientUname))
                                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbltitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBP)
                            .addComponent(lblPulse)
                            .addComponent(lblTemp)
                            .addComponent(lblPresc))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnClear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSave))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(txtBp)
                            .addComponent(txtPulse)
                            .addComponent(txtTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(scrollPaneEncounter, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblBP, lblBloodGroup, lblCreatedBy, lblEncounterNo, lblHospital, lblPatientName, lblPatientUname, lblPresc, lblPulse, lblTemp});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCreate)
                        .addGap(18, 18, 18)
                        .addComponent(btnView)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit1)
                        .addGap(64, 64, 64))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollPaneEncounter, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBP)
                            .addComponent(txtBp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPulse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPulse))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTemp)
                            .addComponent(txtTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPresc)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEncounterNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEncounterNo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHospital)
                            .addComponent(txtHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPatientName))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPatientUname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPatientUname))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCreatedBy)
                            .addComponent(txtDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBloodGroup))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClear)
                    .addComponent(btnSave))
                .addGap(56, 56, 56))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblBP, lblBloodGroup, lblCreatedBy, lblEncounterNo, lblHospital, lblPatientName, lblPatientUname, lblPresc, lblPulse, lblTemp});

    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        //        btnClear.setVisible(false);
        String encounterNo = String.valueOf(txtEncounterNo.getSelectedItem());
        String hospital = String.valueOf(txtHospital.getSelectedItem());
        String createdBy = txtDoctor.getText();
//        String doctorUsername = String.valueOf(txtDoctorUsername.getSelectedItem());
        String patientName = String.valueOf(txtPatientName.getSelectedItem());
        String patientUsername = String.valueOf(txtBloodGroup.getSelectedItem());
//        Integer roomNo = Integer.parseInt(txtRoomNo.getText());
        String bloodGroup = String.valueOf(txtBloodGroup.getSelectedItem());
        Integer bp = Integer.parseInt(txtBp.getText());
        Integer pulse = Integer.parseInt(txtPulse.getText());
        Integer temp = Integer.parseInt(txtTemp.getText());
        String presc = txtPrescription.getText();

        VitalSign newVS = vitalSignList.addVitalSign();

        newVS.setEncounterNo(encounterNo);
        newVS.setHospital(hospital);
        newVS.setDoctorName(createdBy);
//        newVS.setDoctorUserName(doctorUsername);
        newVS.setPatientName(patientName);
        newVS.setPatientUsername(patientUsername);
//        newVS.setRooomNo(roomNo);
//        newVS.setDate(date);
//        newVS.setTime(time);
        newVS.setBloodGroup(bloodGroup);
        newVS.setBp(bp);
        newVS.setPulse(pulse);
        newVS.setTemp(temp);
        newVS.setComment(presc);

        JOptionPane.showMessageDialog(this, "Encounter Created Successfully");

        txtEncounterNo.setSelectedIndex(0);
        txtHospital.setSelectedIndex(0);
//        txtDoctor.setText("");
//        txtDoctorUsername.setSelectedIndex(0);
        txtPatientName.setSelectedIndex(0);
        txtPatientUname.setSelectedIndex(0);
        txtBloodGroup.setSelectedIndex(0);
        txtBp.setText("");
        txtPulse.setText("");
        txtTemp.setText("");
//        txtRoomNo.setText("");
//        txtDate.setText("");
//        txtTime.setText("");
        txtPrescription.setText("");

        populateTable();
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        //        btnSave.setVisible(false);
        btnClear.setVisible(true);
        btnSave.setVisible(false);
        Integer selectedRowIndex = tableVS.getSelectedRow();

        if (selectedRowIndex < 0) {

            JOptionPane.showMessageDialog(this, "Please select a row to view.");
            return;
        } else {
            DefaultTableModel model = (DefaultTableModel) tableVS.getModel();
            VitalSign selectedVS = (VitalSign) model.getValueAt(selectedRowIndex, 0);

            txtEncounterNo.setSelectedItem(String.valueOf(selectedVS.getEncounterNo()));
            txtHospital.setSelectedItem(selectedVS.getHospital());
            txtDoctor.setText(selectedVS.getDoctorName());
//            txtDoctorUsername.setSelectedItem(selectedVS.getDoctorUserName());
            txtPatientName.setSelectedItem(selectedVS.getPatientName());
            txtPatientUname.setSelectedItem(selectedVS.getPatientUsername());
            txtBloodGroup.setSelectedItem(String.valueOf(selectedVS.getBloodGroup()));
//            txtRoomNo.setText(String.valueOf(selectedVS.getRooomNo()));
//            txtDate.setText(selectedVS.getDate());
//            txtTime.setText(selectedVS.getTime());
            txtBp.setText(String.valueOf(selectedVS.getBp()));
            txtPulse.setText(String.valueOf(selectedVS.getPulse()));
            txtTemp.setText(String.valueOf(selectedVS.getTemp()));
            txtPrescription.setText(selectedVS.getComment());

        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit1ActionPerformed
        // TODO add your handling code here:
        btnSave.setVisible(true);
        btnClear.setVisible(true);

        btnClear.setVisible(true);
        Integer selectedRowIndex = tableVS.getSelectedRow();

        if (selectedRowIndex < 0) {

            JOptionPane.showMessageDialog(this, "Please select a row to view.");
            return;
        } else {
            DefaultTableModel model = (DefaultTableModel) tableVS.getModel();
            VitalSign selectedVS = (VitalSign) model.getValueAt(selectedRowIndex, 0);

            txtEncounterNo.setSelectedItem(String.valueOf(selectedVS.getEncounterNo()));
            txtHospital.setSelectedItem(selectedVS.getHospital());
            txtDoctor.setText(selectedVS.getDoctorName());
//            txtDoctorUsername.setSelectedItem(selectedVS.getDoctorUserName());
            txtPatientName.setSelectedItem(selectedVS.getPatientName());
            txtPatientUname.setSelectedItem(selectedVS.getPatientUsername());
            txtBloodGroup.setSelectedItem(String.valueOf(selectedVS.getBloodGroup()));
//            txtRoomNo.setText(String.valueOf(selectedVS.getRooomNo()));
//            txtDate.setText(selectedVS.getDate());
//            txtTime.setText(selectedVS.getTime());
            txtBp.setText(String.valueOf(selectedVS.getBp()));
            txtPulse.setText(String.valueOf(selectedVS.getPulse()));
            txtTemp.setText(String.valueOf(selectedVS.getTemp()));
            txtPrescription.setText(selectedVS.getComment());

        }
    }//GEN-LAST:event_btnEdit1ActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtEncounterNo.setSelectedIndex(0);
        txtHospital.setSelectedIndex(0);
//        txtDoctor.setText("");
//        txtDoctorUsername.setSelectedIndex(0);
        txtPatientName.setSelectedIndex(0);
        txtPatientUname.setSelectedIndex(0);
        txtBloodGroup.setSelectedIndex(0);
        txtBp.setText("");
        txtPulse.setText("");
        txtTemp.setText("");
//        txtRoomNo.setText("");
//        txtDate.setText("");
//        txtTime.setText("");
        txtPrescription.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        Integer selectedRowIndex = tableVS.getSelectedRow();

        if (selectedRowIndex < 0) {

            JOptionPane.showMessageDialog(this, "Please select a row to view.");
            return;
        } else {
            DefaultTableModel model = (DefaultTableModel) tableVS.getModel();
            VitalSign selectedVS = (VitalSign) model.getValueAt(selectedRowIndex, 0);

            selectedVS.setEncounterNo(String.valueOf(txtEncounterNo.getSelectedItem()));
            selectedVS.setHospital(String.valueOf(txtHospital.getSelectedItem()));
            selectedVS.setDoctorName(String.valueOf(txtDoctor.getText()));
//            selectedVS.setDoctorUserName(String.valueOf(txtDoctorUsername.getSelectedItem()));
            selectedVS.setPatientName(String.valueOf(txtPatientName.getSelectedItem()));
            selectedVS.setPatientUsername(String.valueOf((txtBloodGroup.getSelectedItem())));
            selectedVS.setBloodGroup(String.valueOf(txtBloodGroup.getSelectedItem()));
            selectedVS.setBp(Integer.parseInt(txtBp.getText()));
            selectedVS.setPulse(Integer.parseInt(txtPulse.getText()));
            selectedVS.setTemp(Integer.parseInt(txtTemp.getText()));
//            selectedVS.setRooomNo(Integer.parseInt(txtRoomNo.getText()));
//            selectedVS.setDate(txtDate.getText());
//            selectedVS.setTime(txtTime.getText());
            selectedVS.setComment(txtPrescription.getText());

            JOptionPane.showMessageDialog(this, "Vital Sign details updated successfully.");

            populateTable();

        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtEncounterNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEncounterNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEncounterNoActionPerformed

    private void txtDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoctorActionPerformed

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tableVS.getModel();
        model.setRowCount(0);

        for (VitalSign vs : vitalSignList.getVitalSignList()) {

            if (doctor.getUsername().equals(vs.getDoctorUserName())) {
                Object[] row = new Object[6];
                row[0] = vs;
                row[1] = vs.getPatientName();
                row[2] = vs.getBloodGroup();
                row[3] = vs.getBp();
                row[4] = vs.getPulse();
                row[5] = vs.getTemp();

                model.addRow(row);
            }
        }
    }

    public void populateEncounter() {
        String[] enArr = encounterList.enArray();
        DefaultComboBoxModel h = new DefaultComboBoxModel(enArr);
        txtEncounterNo.setModel(h);
    }

    public void populateHospital() {
        String[] hosArr = hospitalList.hosArray();
        DefaultComboBoxModel h = new DefaultComboBoxModel(hosArr);
        txtHospital.setModel(h);
    }

//    public void populateDoctor(){
//        String[] docNameArr = doctorList.docNameArray();
//        DefaultComboBoxModel dn = new DefaultComboBoxModel(docNameArr);
//        txtDoctor.setModel(dn);
//        String[] docUnameArr = doctorList.docUnameArray();
//        DefaultComboBoxModel du = new DefaultComboBoxModel(docUnameArr);
//        txtDoctorUsername.setModel(du);   
//    }
    public void populatePatient() {
        String[] patNameArr = patientList.patNameArray();
        DefaultComboBoxModel pn = new DefaultComboBoxModel(patNameArr);
        txtPatientName.setModel(pn);

        String[] patUnameArr = patientList.patUnameArray();
        DefaultComboBoxModel pu = new DefaultComboBoxModel(patUnameArr);
        txtPatientUname.setModel(pu);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnEdit1;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBP;
    private javax.swing.JLabel lblBloodGroup;
    private javax.swing.JLabel lblCreatedBy;
    private javax.swing.JLabel lblEncounterNo;
    private javax.swing.JLabel lblHospital;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblPatientUname;
    private javax.swing.JLabel lblPresc;
    private javax.swing.JLabel lblPulse;
    private javax.swing.JLabel lblTemp;
    private javax.swing.JLabel lbltitle1;
    private javax.swing.JScrollPane scrollPaneEncounter;
    private javax.swing.JTable tableVS;
    private javax.swing.JComboBox<String> txtBloodGroup;
    private javax.swing.JTextField txtBp;
    private javax.swing.JTextField txtDoctor;
    private javax.swing.JComboBox<String> txtEncounterNo;
    private javax.swing.JComboBox<String> txtHospital;
    private javax.swing.JComboBox<String> txtPatientName;
    private javax.swing.JComboBox<String> txtPatientUname;
    private javax.swing.JTextArea txtPrescription;
    private javax.swing.JTextField txtPulse;
    private javax.swing.JTextField txtTemp;
    // End of variables declaration//GEN-END:variables
}
