/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.HospitalAdminWorkspace;

import Hospital.City.CityDirectory;
import Hospital.Community.CommunityDirectory;
import Hospital.Doctor.Doctor;
import Hospital.Doctor.DoctorDirectory;
import Hospital.Hospital.HospitalDirectory;
import Hospital.Patient.Patient;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kishor
 */
public class HospitalDoctorPanel extends javax.swing.JPanel {
    
    private DoctorDirectory doctorList;
    private CityDirectory cityList;
    private CommunityDirectory communityList;
    private HospitalDirectory hospitalList;
    

    /**
     * Creates new form HospitalDoctorPanel
     */
    public HospitalDoctorPanel(DoctorDirectory doctorList,HospitalDirectory hospitalList,CityDirectory cityList,CommunityDirectory communityList) {
        initComponents();
        this.doctorList = doctorList;
        this.cityList = cityList;
        this.communityList = communityList;
        this.hospitalList = hospitalList;
        populateTable();
        populateCity();
        populateState();
        populateCountry();
        populateComm();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreate = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnEdit1 = new javax.swing.JButton();
        scrollPaneDoctor = new javax.swing.JScrollPane();
        tableDoctor = new javax.swing.JTable();
        lblName = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        txtPhNo1 = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        lblPhNo1 = new javax.swing.JLabel();
        txtRole = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        txtEmailId = new javax.swing.JTextField();
        lblEmailId = new javax.swing.JLabel();
        txtGender = new javax.swing.JComboBox<>();
        txtName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        lblDoctorId = new javax.swing.JLabel();
        txtDoctorId = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblHospital = new javax.swing.JLabel();
        txtHospital = new javax.swing.JComboBox<>();
        lblYearsOfExp = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        txtCity = new javax.swing.JComboBox<>();
        txtYearsOfExp = new javax.swing.JTextField();
        txtCountry = new javax.swing.JComboBox<>();
        lblCountry = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        txtState = new javax.swing.JComboBox<>();
        lblCommunity = new javax.swing.JLabel();
        txtCommunity = new javax.swing.JComboBox<>();
        txtSpecialization = new javax.swing.JTextField();
        lblSpecialization = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lbltitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 0, 102));

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnEdit1.setText("Edit");
        btnEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit1ActionPerformed(evt);
            }
        });

        tableDoctor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Doctor Id", "Name", "Specialization", "Age", "Gender", "Phone No"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrollPaneDoctor.setViewportView(tableDoctor);

        lblName.setText("Name: ");

        lblRole.setText("Role:");

        txtPhNo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhNo1ActionPerformed(evt);
            }
        });

        lblGender.setText("Gender: ");

        lblPhNo1.setText("Phone No: ");

        txtRole.setEditable(false);
        txtRole.setText("Doctor");

        lblAge.setText("Age: ");

        txtEmailId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailIdActionPerformed(evt);
            }
        });

        lblEmailId.setText("Email Id:");

        txtGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Male", "Female", "Others" }));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        lblUsername.setText("Username:");

        lblDoctorId.setText("Doctor Id:");

        lblPassword.setText("Password:");

        lblHospital.setText("Hospital:");

        txtHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHospitalActionPerformed(evt);
            }
        });

        lblYearsOfExp.setText("Years of Experience:");

        lblState.setText("State:");

        txtYearsOfExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYearsOfExpActionPerformed(evt);
            }
        });

        lblCountry.setText("Country:");

        lblCity.setText("City:");

        lblCommunity.setText("Community:");

        txtSpecialization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSpecializationActionPerformed(evt);
            }
        });

        lblSpecialization.setText("Specialization:");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        lbltitle.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        lbltitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitle.setText("HOSPITAL ADMIN: DOCTOR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(scrollPaneDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnClear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSave))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblRole)
                                            .addComponent(lblDoctorId)
                                            .addComponent(lblUsername)
                                            .addComponent(lblName)
                                            .addComponent(lblAge)
                                            .addComponent(lblGender))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblEmailId)
                                            .addGap(11, 11, 11)))
                                    .addComponent(lblPhNo1))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtName)
                                    .addComponent(txtDoctorId)
                                    .addComponent(txtUsername)
                                    .addComponent(txtRole, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPhNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblYearsOfExp)
                                    .addComponent(lblSpecialization)
                                    .addComponent(lblCommunity)
                                    .addComponent(lblCity)
                                    .addComponent(lblState)
                                    .addComponent(lblCountry)
                                    .addComponent(lblPassword)
                                    .addComponent(lblHospital))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtYearsOfExp, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(20, 20, 20)))
                .addGap(64, 64, 64))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitle, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                .addGap(33, 33, 33))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCreate, btnEdit1, btnView});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblAge, lblCity, lblCommunity, lblCountry, lblEmailId, lblGender, lblHospital, lblName, lblPassword, lblPhNo1, lblRole, lblSpecialization, lblState, lblUsername, lblYearsOfExp});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAge, txtCity, txtCommunity, txtCountry, txtDoctorId, txtEmailId, txtGender, txtHospital, txtName, txtPassword, txtPhNo1, txtRole, txtSpecialization, txtState, txtUsername, txtYearsOfExp});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCreate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnView)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEdit1))
                    .addComponent(scrollPaneDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRole))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDoctorId)
                            .addComponent(txtDoctorId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsername)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAge))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGender))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmailId))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPhNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhNo1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCommunity)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCity))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblState)
                                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblHospital)
                                    .addComponent(txtHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSpecialization))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblYearsOfExp)
                                    .addComponent(txtYearsOfExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCountry))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnClear))
                .addGap(21, 21, 21))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCreate, btnEdit1, btnView});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblAge, lblCity, lblCommunity, lblCountry, lblEmailId, lblGender, lblHospital, lblName, lblPassword, lblPhNo1, lblRole, lblSpecialization, lblState, lblUsername, lblYearsOfExp});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtAge, txtCity, txtCommunity, txtCountry, txtDoctorId, txtEmailId, txtGender, txtHospital, txtName, txtPassword, txtPhNo1, txtRole, txtSpecialization, txtState, txtUsername, txtYearsOfExp});

    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        //        btnClear.setVisible(false);
        String role = txtRole.getText();
        Integer doctorId = Integer.parseInt(txtDoctorId.getText());
        String username = txtUsername.getText();
        String name = txtName.getText();
        Integer age = Integer.parseInt(txtAge.getText());
        String gender = String.valueOf(txtGender.getSelectedItem());
        Long phno1 = Long.parseLong(txtPhNo1.getText());
        String email = txtEmailId.getText();
        String hospital = String.valueOf(txtHospital.getSelectedItem());
        String specialization = txtSpecialization.getText();
        //        Long salary = Long.parseLong(txtSalary.getText());
        Integer yearsOfExp = Integer.parseInt(txtYearsOfExp.getText());
        String city = String.valueOf(txtCity.getSelectedItem());
        String community = String.valueOf(txtCommunity.getSelectedItem());
        String state = String.valueOf(txtState.getSelectedItem());
        String country = String.valueOf(txtCountry.getSelectedItem());
        char[] pass = txtPassword.getPassword();
        String password = new String(pass);

        Doctor newDoctor = doctorList.addDoctor();

        newDoctor.setRole(role);
        newDoctor.setDoctorId(doctorId);
        newDoctor.setUsername(username);
        newDoctor.setName(name);
        newDoctor.setAge(age);
        newDoctor.setGender(gender);
        newDoctor.setPhno(phno1);
        newDoctor.setEmail(email);
        newDoctor.setHospital(hospital);
        newDoctor.setSpecialization(specialization);
        newDoctor.setYearsOfExp(yearsOfExp);
        //        newDoctor.setSalary(salary);
        newDoctor.setCity(city);
        newDoctor.setCommunity(community);
        newDoctor.setState(state);
        newDoctor.setCountry(country);
        newDoctor.setPassword(password);

        JOptionPane.showMessageDialog(this, "Doctor Created Successfully");

        txtDoctorId.setText("");
        txtUsername.setText("");
        txtName.setText("");
        txtAge.setText("");
        txtGender.setSelectedIndex(0);
        txtPhNo1.setText("");
        txtEmailId.setText("");
        txtHospital.setSelectedIndex(0);
        txtSpecialization.setText((""));
        txtYearsOfExp.setText("");
        //        txtSalary.setText("");
        txtCity.setSelectedIndex(0);
        txtCommunity.setSelectedIndex(0);
        txtState.setSelectedIndex(0);
        txtCountry.setSelectedIndex(0);
        txtPassword.setText("");

        populateTable();
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        //        btnSave.setVisible(false);
        btnClear.setVisible(true);
        btnSave.setVisible(false);
        Integer selectedRowIndex = tableDoctor.getSelectedRow();

        if (selectedRowIndex<0){

            JOptionPane.showMessageDialog(this, "Please select a row to view.");
            return;
        }

        else{
            DefaultTableModel model = (DefaultTableModel) tableDoctor.getModel();
            Doctor selectedDoc = (Doctor) model.getValueAt(selectedRowIndex,0);

            txtDoctorId.setText(String.valueOf(selectedDoc.getDoctorId()));
            txtUsername.setText(selectedDoc.getUsername());
            txtName.setText(selectedDoc.getName());
            txtAge.setText(String.valueOf(selectedDoc.getAge()));
            txtGender.setSelectedItem(selectedDoc.getGender());
            txtPhNo1.setText(String.valueOf(selectedDoc.getPhno()));
            txtEmailId.setText(selectedDoc.getEmail());
            txtHospital.setSelectedItem(selectedDoc.getHospital());
            txtSpecialization.setText(selectedDoc.getSpecialization());
            txtYearsOfExp.setText(String.valueOf(selectedDoc.getYearsOfExp()));
            //            txtSalary.setText(String.valueOf(selectedDoc.getSalary()));
            txtCity.setSelectedItem(selectedDoc.getCity());
            txtCommunity.setSelectedItem(selectedDoc.getCommunity());
            txtState.setSelectedItem(selectedDoc.getState());
            //            txtAddress.setText(selectedDoc.getAddress());
            txtCountry.setSelectedItem(selectedDoc.getCountry());
            txtPassword.setText(selectedDoc.getPassword());
        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit1ActionPerformed
        // TODO add your handling code here:
        btnSave.setVisible(true);
        btnClear.setVisible(true);

        Integer selectedRowIndex = tableDoctor.getSelectedRow();

        if (selectedRowIndex<0){

            JOptionPane.showMessageDialog(this, "Please select a row to view.");
            return;
        }

        else{
            DefaultTableModel model = (DefaultTableModel) tableDoctor.getModel();
            Doctor selectedDoc = (Doctor) model.getValueAt(selectedRowIndex,0);

            txtDoctorId.setText(String.valueOf(selectedDoc.getDoctorId()));
            txtUsername.setText(selectedDoc.getUsername());
            txtName.setText(selectedDoc.getName());
            txtAge.setText(String.valueOf(selectedDoc.getAge()));
            txtGender.setSelectedItem(selectedDoc.getGender());
            txtPhNo1.setText(String.valueOf(selectedDoc.getPhno()));
            txtEmailId.setText(selectedDoc.getEmail());
            txtHospital.setSelectedItem(selectedDoc.getHospital());
            txtSpecialization.setText(selectedDoc.getSpecialization());
            txtYearsOfExp.setText(String.valueOf(selectedDoc.getYearsOfExp()));
            //            txtSalary.setText(String.valueOf(selectedDoc.getSalary()));
            txtCity.setSelectedItem(selectedDoc.getCity());
            txtCommunity.setSelectedItem(selectedDoc.getCommunity());
            txtState.setSelectedItem(selectedDoc.getState());
            //            txtAddress.setText(selectedDoc.getAddress());
            txtCountry.setSelectedItem(selectedDoc.getCountry());
            txtPassword.setText(selectedDoc.getPassword());

        }
    }//GEN-LAST:event_btnEdit1ActionPerformed

    private void txtPhNo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhNo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhNo1ActionPerformed

    private void txtEmailIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailIdActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtYearsOfExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYearsOfExpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYearsOfExpActionPerformed

    private void txtSpecializationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSpecializationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpecializationActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        Integer selectedRowIndex = tableDoctor.getSelectedRow();

        if (selectedRowIndex<0){

            JOptionPane.showMessageDialog(this, "Please select a row to view.");
            return;
        }

        else{
            DefaultTableModel model = (DefaultTableModel) tableDoctor.getModel();
            Doctor selectedDoc = (Doctor) model.getValueAt(selectedRowIndex,0);

            selectedDoc.setDoctorId(Integer.parseInt(txtDoctorId.getText()));
            selectedDoc.setUsername(txtUsername.getText());
            selectedDoc.setName(txtName.getText());
            selectedDoc.setAge(Integer.parseInt(txtAge.getText()));
            selectedDoc.setGender(String.valueOf(txtGender.getSelectedItem()));
            selectedDoc.setPhno(Long.parseLong(txtPhNo1.getText()));
            selectedDoc.setEmail(txtEmailId.getText());
            selectedDoc.setSpecialization(txtSpecialization.getText());
            selectedDoc.setHospital(String.valueOf(txtHospital.getSelectedItem()));
            selectedDoc.setYearsOfExp(Integer.parseInt(txtYearsOfExp.getText()));
            //            selectedDoc.setSalary(Long.parseLong(txtSalary.getText()));
            selectedDoc.setCity(String.valueOf(txtCity.getSelectedItem()));
            selectedDoc.setCommunity(String.valueOf(txtCommunity.getSelectedItem()));
            selectedDoc.setState(String.valueOf(txtState.getSelectedItem()));
            //            selectedDoc.setAddress(txtAddress.getText());
            selectedDoc.setCountry(String.valueOf(txtCountry.getSelectedItem()));
            selectedDoc.setPassword(txtPassword.getText());

            JOptionPane.showMessageDialog(this, "Doctor details updated successfully.");

            populateTable();

        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtDoctorId.setText("");
        txtUsername.setText("");
        txtName.setText("");
        txtAge.setText("");
        txtGender.setSelectedIndex(0);
        txtPhNo1.setText("");
        txtEmailId.setText("");
        txtHospital.setSelectedIndex(0);
        txtSpecialization.setText((""));
        txtYearsOfExp.setText("");
        //        txtSalary.setText("");
        txtCity.setSelectedIndex(0);
        txtCommunity.setSelectedIndex(0);
        txtState.setSelectedIndex(0);
        txtCountry.setSelectedIndex(0);
        txtPassword.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHospitalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHospitalActionPerformed

    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) tableDoctor.getModel();
        model.setRowCount(0);
        
        for(Doctor doc : doctorList.getDoctorList()){
            
            Object[] row = new Object[5];
            row[0] = doc;
            row[1] = doc.getName();
            row[2] = doc.getSpecialization();
            row[3] = doc.getAge();
            row[4] = doc.getGender();
            row[5] = doc.getPhno();
             
            model.addRow(row);
        }
    }
     
    public void populateHospital(){
        String[] hosArr = hospitalList.hosArray();
        DefaultComboBoxModel h = new DefaultComboBoxModel(hosArr);
        txtHospital.setModel(h);
    }
    
    public void populateCity(){
        String[] cityArr = cityList.cityArray();
        DefaultComboBoxModel c = new DefaultComboBoxModel(cityArr);
        txtCity.setModel(c);
    }
    
    public void populateState(){
        String[] stateArr = cityList.stateArray();
        DefaultComboBoxModel s = new DefaultComboBoxModel(stateArr);
        txtState.setModel(s);
    }
    
    public void populateCountry(){
        String[] countryArr = cityList.countryArray();
        DefaultComboBoxModel c = new DefaultComboBoxModel(countryArr);
        txtCountry.setModel(c);
    }
    
     public void populateComm(){
        String[] commArr = communityList.commArray();
        DefaultComboBoxModel c = new DefaultComboBoxModel(commArr);
        txtCommunity.setModel(c);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnEdit1;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCommunity;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblDoctorId;
    private javax.swing.JLabel lblEmailId;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHospital;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPhNo1;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblSpecialization;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblYearsOfExp;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JScrollPane scrollPaneDoctor;
    private javax.swing.JTable tableDoctor;
    private javax.swing.JTextField txtAge;
    private javax.swing.JComboBox<String> txtCity;
    private javax.swing.JComboBox<String> txtCommunity;
    private javax.swing.JComboBox<String> txtCountry;
    private javax.swing.JTextField txtDoctorId;
    private javax.swing.JTextField txtEmailId;
    private javax.swing.JComboBox<String> txtGender;
    private javax.swing.JComboBox<String> txtHospital;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPhNo1;
    private javax.swing.JTextField txtRole;
    private javax.swing.JTextField txtSpecialization;
    private javax.swing.JComboBox<String> txtState;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtYearsOfExp;
    // End of variables declaration//GEN-END:variables
}
